### ISSUE TITLE
access denied when pulling docker image

### ISSUE THREAD

**Issue by woogi-kang** [Nimdy/VRising_Dedicated_Docker_Server#2]
![image](https://user-images.githubusercontent.com/70678014/174612488-c13bdbed-347c-4505-91ff-c962d09f6cfc.png)

Hello, thanks for your repository.

Could you please make the Docker image public? I am having this error when I am trying to run docker in GCP

**Comment by Nimdy** [comment]
its not a public file. This dockerfile is created locally when you build it by using:

` sudo docker build . -t njordmenu/vrising:latest`
